updated dbfs benchs script to have number of processes

diff --git a/benchs/scripts/dbfs b/benchs/scripts/dbfs
--- a/benchs/scripts/dbfs
+++ b/benchs/scripts/dbfs
@@ -1,54 +1,48 @@
 #!/bin/bash
 
 N=$1
-HS=$2
+P=$2
 
-T=28
-H=268435456
+# H = max hash table size and T = log_2(H)
+T=29
+H=$(echo "2 ^ $T" | bc)
 
 # some checks
 [ -z "$N" ] && echo "missing \$1 = # of nodes" && exit 1
-[ -z "$HS" ] && echo "missing \$2 = shmem heap size" && exit 1
+[ -z "$P" ] && echo "missing \$2 = # of procs per node" && exit 1
 [ -z "$OAR_NODEFILE" ] && echo 'not in an OAR job' && exit 1
+[ $(cat $OAR_NODEFILE | wc -l) -lt $N ] && echo "not enough machines" && exit 1
 
-helena="helena --algo=dbfs --machine-file=machinefile -hs=$HS -C"
-outDir=out/dbfs-$HS
+helena="helena --algo=dbfs --machine-file=$OAR_NODEFILE -hs=10000000 -C --progress=no-report"
+outDir=out/dbfs
 mkdir -p $outDir &> /dev/null
 
-models='elevator.5;dve;185008051;22
-lifts.9;dve;266445936;22
-firewire_link.3;dve;425333983;22
-leader_filters.8;dve;431401020;22
-collision.5;dve;431965993;22
-iprotocol.8;dve;447570146;22
-anderson.8;dve;538699029;22
-telephony.8;dve;1051746064;24
-public_subscribe.5;dve;1153014089;22
-lamport.9;dve;1436848880;22
-brp.8;dve;1526547707;22
-synapse.9;dve;1675298471;22
-szymanski.6;dve;6779809484;22'
+models='elevator.5;185008051;22
+lifts.9;266445936;22
+firewire_link.3;425333983;22
+leader_filters.8;431401020;22
+collision.5;431965993;22
+iprotocol.8;447570146;22
+anderson.8;538699029;22
+telephony.8;1051746064;24
+public_subscribe.5;1153014089;22
+lamport.9;1436848880;22
+brp.8;1526547707;22
+synapse.9;1675298471;22
+szymanski.6;6779809484;22'
 
-for N in $(seq $N -2 2)
+for N in $(seq $N -2 2) 1
 do
-    for P in 8 4 2 1
+    for P in $(seq $P -2 2) 1
     do
-	cat $OAR_NODEFILE | sort -u | head -$N | \
-	    while read host
-	    do
-		echo "$host max-slots=$P"
-	    done > machinefile
-	MAX=$(cat machinefile | wc -l)
-	[ $MAX -lt $N ] && echo "not enough machines" && exit 1
+	[ $P = 1 -a $P = 1 ] && continue
 	for l in $models
 	do
-	    m=$(echo $l | cut -f1 -d';')
-	    lang=$(echo $l | cut -f2 -d';')
-	    st=$(echo $l | cut -f3 -d';')
-	    cb=$(echo $l | cut -f4 -d';')
-	    f=$(scripts/get-file $m $lang)
+	    m=$(echo $l  | cut -f1 -d';')
+	    st=$(echo $l | cut -f2 -d';')
+	    cb=$(echo $l | cut -f3 -d';')
+	    f=$(scripts/get-file $m dve)
 	    [ ! -f $f ] && continue
-	    param=$(scripts/format-parameters $opt)
 	    [ $st -gt $((N * H * 50 / 100)) ] && continue
 	    p=$P
 	    t=$T
@@ -57,16 +51,10 @@ do
 		p=$((p / 2))
 		t=$((t - 1))
 	    done
-	    xml=$outDir/$m
-	    if [ "$opt" != "" ]
-	    then
-		xml=$xml-$(echo $opt | tr " " "-")
-	    fi
-	    xml=$xml"_N"$N"_P"$P".xml"
+	    xml=$outDir/$m"_N"$N"_P"$P".xml"
 	    [ -f $xml ] && continue
-	    cmd=$helena" -t=$t -cb=$cb "$param
-	    cmd=$cmd" --progress=no-report --report-file="$xml" $f"
-	    echo '***** '$m - $st states' *****'
+	    cmd=$helena" -t=$t -cb=$cb --report-file=$xml -np=$P $f"
+	    echo "***** MODEL=$m - NODES=$N - PROCESSES=$P *****"
 	    echo $cmd
 	    eval $cmd
 	done
