updated dbfs benchs script to take care of cases when we are not allowed enough machines

diff --git a/benchs/scripts/dbfs b/benchs/scripts/dbfs
--- a/benchs/scripts/dbfs
+++ b/benchs/scripts/dbfs
@@ -1,5 +1,5 @@
 #!/bin/bash
-#OAR -l nodes=8/cpu=2,walltime=10:00:00
+#OAR -l nodes=10,walltime=10:00:00
 #OAR -p ib='QDR'
 #OAR -t allow_classic_ssh
 #OAR -n dist-helena
@@ -9,23 +9,26 @@
 [ "$1" = "" ] && echo 'error: missing $1 = # of nodes' && exit 1
 [ "$2" = "" ] && echo 'error: missing $2 = min # of states' && exit 1
 [ "$3" = "" ] && echo 'error: missing $3 = max # of states' && exit 1
-[ "$4" = "" ] && echo 'error: missing $4 = hash-compaction (0/1)' && exit 1
+[ "$4" = "" ] && echo 'error: missing $4 = btl' && exit 1
 
 MAXW=$1
 minStates=$2
 maxStates=$3
-hc=$4
+btl=$4
+
+helena=helena
 
 export PATH=$HOME/helena/bin:$PATH
 
-# create base helena command
-if [ $hc = 1 ]
+if [ $btl = tcp ]
 then
-    helena="helena --hash-compaction=1"
-    outDir=out/dbfs-hc
+    outDir=out/dbfs-tcp
+elif [  $btl = ib ]
+then
+    outDir=out/dbfs-ib
 else
-    helena=helena
-    outDir=out/dbfs
+    echo 'error: unkown BTL :'$btl
+    exit 1
 fi
 
 #  create the machine file
@@ -43,15 +46,19 @@ else
     done > machinefile
 fi
 
-#  launch helena and kill it after 60 seconds if the search does not
-#  progress (happens sometimes because shmem_init does not terminate)
+# check how much nodes I have been given (may be less than what I
+# asked)
+MAXW=$(cat machinefile | wc -l)
+
+# launch helena and kill it after MAX seconds if the search does not
+# progress (happens sometimes because shmem_init does not terminate)
 launchHelena () {
     cmd=$*
     echo $cmd
     tmp=$(mktemp)
     eval $cmd > $tmp &
     pid=$!
-    MAX=60
+    MAX=15
     n=1
     while [ $n -lt $MAX ]
     do
@@ -66,6 +73,7 @@ launchHelena () {
     done
     if [ $n -ge $MAX ]
     then
+	echo "***** wait for $pid *****"
 	wait $pid
 	cat $tmp
     else
@@ -105,13 +113,7 @@ scripts/select-models $minStates $maxStates \
 		  if [ $N -gt 1 ]
 		  then
 		      head -$N machinefile > mf
-		      C=$(($N / 4))
-		      if [ $(($N % 4)) != 0 ]
-		      then
-			  C=$(($C + 1))
-		      fi
-                      C=1
-		      cmd=$cmd" --algo=dbfs --machine-file=mf --comm-workers="$C
+		      cmd=$cmd" --algo=dbfs --machine-file=mf"
 		  else
 		      cmd=$cmd" --algo=bfs"
 		  fi
@@ -128,5 +130,5 @@ scripts/select-models $minStates $maxStates \
 
 if [ $reports != $(ls -1 $outDir | wc -l) ]
 then
-    scripts/dbfs $MAXW $minStates $maxStates $hc
+    scripts/dbfs $MAXW $minStates $maxStates $btl
 fi
