improved ddfs benchmark script

diff --git a/benchs/scripts/ddfs b/benchs/scripts/ddfs
--- a/benchs/scripts/ddfs
+++ b/benchs/scripts/ddfs
@@ -1,6 +1,18 @@
 #!/bin/bash
+#OAR -l nodes=8,walltime=10:00:00
+#OAR -p ib='QDR'
+#OAR -t allow_classic_ssh
+#OAR -n dist-helena
+#OAR -O ddfs.out
+#OAR -E ddfs.err
 
-MAXW=8
+[ "$1" = "" ] && echo 'error: missing $1 = # of nodes' && exit 1
+[ "$2" = "" ] && echo 'error: missing $2 = min # of states' && exit 1
+[ "$3" = "" ] && echo 'error: missing $3 = max # of states' && exit 1
+
+MAXW=$1
+minStates=$2
+maxStates=$3
 
 export PATH=$HOME/helena/bin:$PATH
 
@@ -18,44 +30,56 @@ else
     done > machinefile
 fi
 
-minStates=10000000
-maxStates=100000000
 outDir=out/ddfs
 mkdir -p $outDir &> /dev/null
+
+reports=$(ls -1 $outDir | wc -l)
+
 scripts/select-models $minStates $maxStates \
     | while read m lang st opt
       do
-	  echo $m - $st states
-	  hashSize=21
-	  size=1048576
+	  printed=0
+	  hashSize=20
+	  size=900000
 	  while [ $size -lt $st -a $hashSize != 30 ]
 	  do
 	      hashSize=$((hashSize + 1))
 	      size=$((size * 2))
 	  done
 	  f=$(scripts/get-file $m $lang)
+	  [ ! -f $f ] && continue
 	  param=$(scripts/format-parameters $opt)
-	  for N in $(seq 2 $MAXW)
+	  for N in $(seq 1 $MAXW)
 	  do
 	      xml=$outDir/$m
 	      if [ "$opt" != "" ]
 	      then
 		  xml=$xml-$(echo $opt | tr " " "-")
 	      fi
-	      xml=$xml-$N.xml
-	      if [ ! -e $xml ]
+	      xml=$xml"_N"$N.xml
+	      if [ ! -f $xml ]
 	      then
 		  cmd="helena --hash-size=$hashSize "$param
 		  if [ $N -gt 1 ]
 		  then
 		      head -$N machinefile > mf
-		      cmd=$cmd" --algo=ddfs --machine-file=mf"
+                      cmd=$cmd" --algo=ddfs --machine-file=mf"
 		  else
 		      cmd=$cmd" --algo=dfs"
 		  fi
 		  cmd=$cmd" --progress=no-report --report-file="$xml" $f"
-		  echo $cmd
-                  eval $cmd &> /dev/null
+		  if [ $printed -eq 0 ]
+		  then
+		      printed=1
+		      echo '***** '$m - $st states' *****'
+		  fi
+                  echo $cmd
+		  eval $cmd # &> /dev/null
 	      fi
 	  done
       done
+
+if [ $reports != $(ls -1 $outDir | wc -l) ]
+then
+    scripts/ddfs $MAXW $minStates $maxStates
+fi
